### ISSUE TITLE
Modify interface to take parameters as reference

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-client-rust#31]
Most parameters get owned by the client once a method call is performed - this could/should be changed so that most parameters are instead passed by reference. The client can clone whatever it needs inside the methods.

The question is whether data buffers that we would normally own and zeroize on drop should be passed as references too.

**Comment by ionut-arm** [comment]
@hug-dev would this impact the SE driver in a major way?

**Comment by hug-dev** [comment]
> this could/should be changed so that most parameters are instead passed by reference.

what do you think would be the advantages of this? Do you have any examples in mind?

> @hug-dev would this impact the SE driver in a major way?

I don't think so! It can adapt 😃

**Comment by ionut-arm** [comment]
> what do you think would be the advantages of this? Do you have any examples in mind?

Yeah, the key name is a big example - we take it as an owned string everywhere... it would be much nicer and idiomatic for a user to just do `&key_name` instead of `key_name.clone()` every time. But pretty much all other attributes (e.g. `AsymmetricEncryption` for sign and verify) do the same

**Comment by hug-dev** [comment]
> Yeah, the key name is a big example - we take it as an owned string everywhere... it would be much nicer and idiomatic for a user to just do &key_name instead of key_name.clone() every time.

Definitely agree for the name! For the other non-Copy type, I guess we will have to review them on a case-by-case basis. Basically it only depends if the client needs to re-use the values after calling the function.

**Comment by hug-dev** [comment]
I guess the default should be to take references everywhere unless the types are `Copy`.
For `String` it should be `&str` and for `Vec<u8>` `&[u8]`

**Comment by ionut-arm** [comment]
I think we've debated this before - passing by reference ends up "hiding" the fact that you actually want an instance of that data and that you're going to clone it. I don't know if it's sensible to just assume that if a type implements `Clone` we can treat a reference the same way as an owned instance.

**Comment by hug-dev** [comment]
I think most `BasicClient` methods take references to buffers now. The thing that would be nice is to use `&str` instead of `String` for keys as the latter implies making `.clone` everywhere... Ideally the clone should be done at the end to hide the complexity before.

Renaming this issue to that.
