### ISSUE TITLE
Implement new authenticator support

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-client-rust#41]
Implement support for the `ListAuthenticators` operation and support for handling a new authenticator type (UDS peer credentials), on the back of changes done in https://github.com/parallaxsecond/parsec-interface-rs/issues/70 . 

Determine if the `BasicClient` should identify a mismatch between the selected app identity type and the existing authenticator.

**Comment by hug-dev** [comment]
We do checks in the clients that the socket folder is grouped owned by `parsec-clients` for direct authentication. Based on the group owner of the socket foldre and its permission, the client could choose the correct authentication method:
* the socket is group-owned by `parsec-client` and is `0o750` -> direct authentication is used
* if not -> Unix peer credentials (or others auth) is used

**Comment by hug-dev** [comment]
Implement on the `AuthenticationData` structure methods to create new instances for the auth type chosen, for example populating the current UID.
