### ISSUE TITLE
Implement component bootstrapping

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-client-rust#52]
The service now offers operations that can be used to bootstrap the client library into using the recommended provider and the supported authentication method. 

Currently the users of `BasicClient` need to make those calls themselves and then configure the client object, but there's no reason that functionality cannot be implemented on top of or into `BasicClient` to limit code duplication.

A design proposal should be made before this can be started.

**Comment by hug-dev** [comment]
In the `BasicClient` we would add two methods:
* `set_default_provider`: will set the first provider returned by `ListProviders`
* `set_default_auth_data`: will set the appropriate auth data based on the first auth type returned by `ListAuthenticators`

In the `new` constructor: set the two defaults.

**Comment by ionut-arm** [comment]
Do you think we should have `new` set the defaults or should we leave it as is and only call the `default` methods in `Default::default()`?

**Comment by ionut-arm** [comment]
It's a bit annoying that there's no method overloading in Rust... :( would've been nice to have one `new` with an `AppIdentity` param and one without.

**Comment by hug-dev** [comment]
Maybe there could be different kind of constructions:
* `new` with no paramaters choosing everything for you
* `new_with_auth_data`: setting only the auth data
* etc...

Implementing `Default` might be hard on types if you don't have access to a client to call `ListProviders` or `ListAuthenticators`?

**Comment by ionut-arm** [comment]
> Implementing Default might be hard on types if you don't have access to a client to call ListProviders or ListAuthenticators?

? I think you can just create a client, call the methods on it and return it. That's what `new` will do as well.

**Comment by ionut-arm** [comment]
Done in #58
