### ISSUE TITLE
Un-versioned SPIFFE dependency prevents publishing crate at version 0.12.0

### ISSUE THREAD

**Issue by paulhowardarm** [parallaxsecond/parsec-client-rust#64]
### Summary
The dependencies for this crate currently include a specific git reference for `rust-spiffe`, which means that `cargo publish` refuses to publish the crate. There is a desire to publish this crate at version `0.12.0` in order to consume `parsec-interface-rs` at `0.22.0` and (indirectly) `psa-crypto` at `0.6.1`. This publication is needed to unblock the PR incoming to add the first pieces of CryptoAuthLib support.

### Details
This crate was incremented to version `0.12.0` with this PR: https://github.com/parallaxsecond/parsec-client-rust/pull/63 

A tag `0.12.0` was created at this commit level: https://github.com/parallaxsecond/parsec-client-rust/commit/2fd8770631f3fb44d64ddf1068f0c0ac49a8fa73

An attempt was made to `cargo publish` the crate, which failed due to the unversioned `rust-spiffe` dependency.

Because the publication failed, the `0.12.0` was later removed to avoid confusion later.

There remains the need to publish and tag the `0.12.0` release, but the SPIFFE dependency needs to be fixed first.

**Comment by hug-dev** [comment]
Even if we put the `spiffe` dependency out of the `default` one, I am not sure the package can even be published. I tried locally but it did not work.
I think that if we want to publish a new version of the Rust client *before* `rust-spiffe` itself is published, we would have to put the SPIFFE related changes in a separate branch from `master` and only publish `master`.

**Comment by hug-dev** [comment]
Solved by #68 and #69, the spiffe stuff has been moved to the `spiffe` branch
